name: Google Cloud Node Executor
version: 1
rundeckPluginVersion: 1.2
author: Jake Cohen / Justyn Roberts / Giran Moodley
date: 2021-11-19
url: http://rundeck.org/
providers:
  - name: GoogleCloudNodeExecutor
    service: NodeExecutor
    plugin-type: script
    script-interpreter: /bin/bash
    script-file: gcloud_node_executor.sh
    script-args: ${node.hostname} ${exec.command} ${config.gcp_service_account_token} ${config.service_account} ${gcp_iaptunnelling} ${gcp_additionalcli} ${gcp_zone} ${gcp_project} ${gcp_tmpdir} ${gcp_gcloud_path}
    config:
      - name: gcp_service_account_token
        type: String
        title: GCloud Service Account Token
        description: "JSON Token for GCloud Service Account"
        renderingOptions:
          selectionAccessor: STORAGE_PATH
          valueConversion: STORAGE_PATH_AUTOMATIC_READ
          instance-scope-node-attribute: gcp_service_account_token
      - name: gcp_iaptunnelling
        type: Boolean
        title: "IAP Tunnelling"
        default: false
        description: "Initialise Identity Aware Proxy (IAP) before execution"
        renderingOptions:
          grouping: secondary
          groupName: "Advanced Options"
          instance-scope-node-attribute: gcp_iaptunnelling
      - name: gcp_additionalcli
        type: String
        title: "Additional Command line options"
        description: "Add additional CLI options. Please use with care."
        renderingOptions:
          grouping: secondary
          groupName: "Advanced Options"
          instance-scope-node-attribute: gcp_additionalcli
      - name: projectId
        type: String
        title: "GCP Project ID"
        description: "GCP Project"
        renderingOptions:
          grouping: secondary
          groupName: "Advanced Options"
          instance-scope-node-attribute: projectId
      - name: gcp_tmpdir
        type: String
        title: "Local Temp Directory"
        default: "/tmp/rundeck/"
        description: "Temp Directory for key creation etc"
        renderingOptions:
          grouping: secondary
          groupName: "Advanced Options"
          instance-scope-node-attribute: gcp_tmpdir
      - name: gcp_gcloud_path
        type: String
        title: "gcloud path"
        default: "/bin/gcloud"
        description: "location containing gcloud executable. Please ensure a trailing /"
        renderingOptions:
          grouping: secondary
          groupName: "Advanced Options"
          instance-scope-node-attribute: gcp_gcloud_path
  - name: GoogleCloudFileCopier
    service: FileCopier
    plugin-type: script
    script-interpreter: /bin/bash
    script-file: gcloud_file_copier.sh
    script-args: ${node.hostname} ${file-copy.file} ${file-copy.destination} ${config.json_token_file} ${config.service_account}${gcp_iaptunnelling} ${gcp_additionalcli} ${gcp_zone} ${gcp_project} ${gcp_tmpdir} ${gcp_gcloud_path}
    config:
      - name: gcp_service_account_token
        type: String
        title: GCloud JSON Token
        description: "JSON Token for GCloud Service Account"
        instance-scope-node-attribute: gcp_service_account_token
      - name: gcp_iaptunnelling
        type: Boolean
        title: "IAP Tunnelling"
        default: false
        description: "Initialise Identity Aware Proxy (IAP) before execution"
        renderingOptions:
          grouping: secondary
          groupName: "Advanced Options"
          instance-scope-node-attribute: gcp_iaptunnelling
      - name: gcp_additionalcli
        type: String
        title: "Additional Command line options"
        description: "Add additional CLI options. Please use with care."
        renderingOptions:
          grouping: secondary
          groupName: "Advanced Options"
          instance-scope-node-attribute: gcp_additional_cli
      - name: projectId
        type: String
        title: "GCP Project ID"
        description: "GCP Project"
        renderingOptions:
          grouping: secondary
          groupName: "Advanced Options"
          instance-scope-node-attribute: projectId
      - name: gcp_tmpdir
        type: String
        title: "Local Temp Directory"
        default: "/tmp/rundeck/"
        description: "Temp Directory for key creation etc"
        renderingOptions:
          grouping: secondary
          groupName: "Advanced Options"
          instance-scope-node-attribute: gcp_tmpdir
      - name: gcp_gcloud_path
        type: String
        title: "gcloud path"
        default: "/bin/gcloud"
        description: "Location containing gcloud executable. Please ensure a trailing /"
        renderingOptions:
          grouping: secondary
          groupName: "Advanced Options"
          instance-scope-node-attribute: gcp_gcloud_path
